site_name: D4D tools

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - toc.follow
    - navigation.indexes
  custom_dir: overrides

repo_url: https://github.com/openkfw/d4dtools
edit_uri: edit/main/docs/

nav:
  - Introduction: "index.md"
  - "disclaimer.md"
  - Contributing: "contributing.md"
  - FAQ: "tech-faq.md"
  - "Fact sheets":
    - general/bim.md
    - general/cameras.md
    - general/collaboration.md
    - general/cst.md
    - general/drones.md
    - general/elearning.md
    - general/gis.md
    - general/mms.md
    - general/mdc.md
    - general/rmis.md
    - general/satellites.md
    - general/sensors.md
  - "Climate resilience":
    - climate-resilience/index.md
    - "Introduction":
      - climate-resilience/Introduction/intro.md
      - climate-resilience/Introduction/solutions-resilience.md
      - climate-resilience/Introduction/opportunities.md
      - climate-resilience/Introduction/challenges.md
    - "Fact sheets":
      - climate-resilience/fact-sheets-cres/ai.md
      - climate-resilience/fact-sheets-cres/data-sources.md
      - climate-resilience/fact-sheets-cres/digital-twins.md
      - climate-resilience/fact-sheets-cres/communication.md
      - climate-resilience/fact-sheets-cres/eot.md
      - climate-resilience/fact-sheets-cres/mobile-tools.md
      - climate-resilience/fact-sheets-cres/rmis-cres.md
      - climate-resilience/fact-sheets-cres/iot.md
    - Summary on Integration of different Tool Types: "climate-resilience/integration.md"

markdown_extensions:
  - toc
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
