site_name: D4D tools

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - toc.follow
  custom_dir: overrides

repo_url: https://github.com/openkfw/d4dtools
edit_uri: edit/main/docs/

nav:
  - Introduction: "index.md"
  - "mdc.md"
  - "gis.md"
  - "bim.md"
  - "disclaimer.md"

markdown_extensions:
    - toc
